# coding=utf-8
# Copyright 2018 Sascha Schirra
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" A ND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from ropper.gadget import Category, Gadget
from ropper.common.error import *
from ropper.common.utils import *
from ropper.rop import Ropper
from ropper.arch import x86_64
from ropper.ropchain.ropchain import *
from ropper.loaders.loader import Type
from ropper.loaders.elf import ELF
from ropper.loaders.pe import PE
from ropper.loaders.raw import Raw
from ropper.loaders.mach_o import MachO
from re import match
import itertools
import math
import sys
import capstone

if sys.version_info.major == 2:
    range = xrange

class RopChainX86_64(RopChain):

    MAX_QUALI = 7

    def _printHeader(self):
        toReturn = ''
        toReturn += ('#!/usr/bin/env python\n')
        toReturn += ('# Generated by ropper ropchain generator #\n')
        toReturn += ('from struct import pack\n')
        toReturn += ('\n')
        toReturn += ('p = lambda x : pack(\'Q\', x)\n')

        toReturn += ('\n')

        return toReturn

    def _printRebase(self):
        toReturn = ''

        for binary,section in self._usedBinaries:
            imageBase = Gadget.IMAGE_BASES[binary]
            toReturn += ('IMAGE_BASE_%d = %s # %s\n' % (self._usedBinaries.index((binary, section)),toHex(imageBase ,8), binary))
            toReturn += ('rebase_%d = lambda x : p(x + IMAGE_BASE_%d)\n\n'% (self._usedBinaries.index((binary, section)),self._usedBinaries.index((binary, section))))
        return toReturn

    @classmethod
    def name(cls):
        return ''

    @classmethod
    def availableGenerators(cls):
        return [RopChainSystemX86_64, RopChainSpawnShellX86_64, RopChainMprotectX86_64, RopChainRet2CsuX86_64]

    @classmethod
    def archs(self):
        return [x86_64]

    def _createDependenceChain(self, gadgets):
        """
        gadgets - list with tuples

        tuple contains:
        - method to create chaingadget
        - list with arguments
        - dict with named arguments
        - list with registers which are not allowed to override in the gadget
        """
        failed = []
        cur_len = 0
        cur_chain = ''
        counter = 0

        max_perm = math.factorial(len(gadgets))
        for x in itertools.permutations(gadgets):
            counter += 1
            self._printMessage('[*] Try permuation %d / %d' % (counter, max_perm))
            found = False
            for y in failed:

                if x[:len(y)] == y:
                    found = True
                    break
            if found:
                continue
            try:
                fail = []
                chain2 = ''
                dontModify = []
                badRegs = []
                c = 0
                for idx in range(len(x)):
                    g = x[idx]
                    if idx != 0:
                        badRegs.extend(x[idx-1][3])

                    dontModify.extend(g[3])
                    fail.append(g)
                    chain2 += g[0](*g[1], badRegs=badRegs, dontModify=dontModify,**g[2])[0]


                cur_chain += chain2
                break

            except RopChainError as e:
                pass
            if len(fail) > cur_len:
                cur_len = len(fail)
                cur_chain = '# Filled registers: '
                for fa in fail[:-1]:

                    cur_chain += (fa[2]['reg']) + ', '
                cur_chain += '\n'
                cur_chain += chain2

            failed.append(tuple(fail))
        else:
            self._printMessage('')
            self._printMessage('Cannot create chain which fills all registers')
        self._printMessage('')
        return cur_chain

    def _isModifiedOrDereferencedAccess(self, gadget, dontModify):

        regs = []
        for line in gadget.lines[1:]:
            line = line[1]
            if '[' in line:
                return True
            if dontModify:
                m = match('[a-z]+ (e?[abcds][ixlh]),?.*', line)
                if m and m.group(1) in dontModify:
                    return True

        return False



    def _paddingNeededFor(self, gadget):
        regs = []
        for idx in range(1,len(gadget.lines)):
            line = gadget.lines[idx][1]
            # 2-3 register chars so the extended regs r8/r9 are counted too
            # (the old `(...)` matched exactly 3 chars and silently dropped
            # `pop r8` / `pop r9`, under-padding the chain).
            matched = match(r'^pop (\w{2,3})$', line)
            if matched:
                regs.append(matched.group(1))
        return regs


    def _printRopInstruction(self, gadget, padding=True, value=None):
        toReturn = ('rop += rebase_%d(%s) # %s\n' % (self._usedBinaries.index((gadget.fileName, gadget.section)),toHex(gadget.lines[0][0],8), gadget.simpleString()))

        value_first = False

        if padding:
            regs = self._paddingNeededFor(gadget)

            if len(regs) > 0:
                dst = gadget.category[2]['dst']
                search = '^pop (%s)$' % dst
                first_line = gadget.lines[0][1]
                if match(search, first_line):
                    value_first = True

            padding_str = ''
            for i in range(len(regs)):
                padding_str +=self._printPaddingInstruction()

            if value_first:
                toReturn += value
                toReturn += padding_str
            else:
                toReturn += padding_str
                if value:
                    toReturn += value

        return toReturn

    def _printAddString(self, string):
        return ('rop += \'%s\'\n' % string)

    def _printRebasedAddress(self, addr, comment='', idx=0):
        return ('rop += rebase_%d(%s)\n' % (idx,addr))

    def _printPaddingInstruction(self, addr='0xdeadbeefdeadbeef'):
        return ('rop += p(%s)\n' % addr)

    def _containsZeroByte(self, addr):
        return self.containsBadbytes(addr,8)

    def _createZeroByteFillerForSub(self, number):
        start = 0x0101010101010101
        for i in range(start, 0x0202020202020202):
            if not self._containsZeroByte(i) and not self._containsZeroByte(i+number):
                return i

    def _createZeroByteFillerForAdd(self, number):
        start = 0x0101010101010101
        for i in range(start, 0x0202020202020202):
            if not self._containsZeroByte(i) and not self._containsZeroByte(number-i):
                return i

    def _find(self, category, reg=None, srcdst='dst', badDst=[], badSrc=None, dontModify=None, srcEqDst=False, switchRegs=False ):
        quali = 1

        if reg and reg[0] != 'r':
            return
        while quali < RopChainSystemX86_64.MAX_QUALI:
            for binary in self._binaries:
                for gadget in self._gadgets[binary]:

                    if gadget.category[0] == category and gadget.category[1] == quali:

                        if badSrc and (gadget.category[2]['src'] in badSrc \
                                       or gadget.affected_regs.intersection(badSrc)):
                            continue
                        if badDst and (gadget.category[2]['dst'] in badDst \
                                       or gadget.affected_regs.intersection(badDst)):
                            continue
                        if not gadget.lines[len(gadget.lines)-1][1].strip().endswith('ret') or 'esp' in gadget.simpleString() or 'rsp' in gadget.simpleString():
                            continue
                        if srcEqDst and (not (gadget.category[2]['dst'] == gadget.category[2]['src'])):
                            continue
                        elif not srcEqDst and 'src' in gadget.category[2] and (gadget.category[2]['dst'] == gadget.category[2]['src']):
                            continue
                        if self._isModifiedOrDereferencedAccess(gadget, dontModify):
                            continue
                        if reg:
                            if gadget.category[2][srcdst] == reg:
                                self._updateUsedBinaries(gadget)
                                return gadget
                            elif switchRegs:
                                other = 'src' if srcdst == 'dst' else 'dst'
                                if gadget.category[2][other] == reg:
                                    self._updateUsedBinaries(gadget)
                                    return gadget
                        else:
                            self._updateUsedBinaries(gadget)
                            return gadget

            quali += 1


    def _createWriteStringWhere(self, what, where, reg=None, dontModify=[], idx=0):
        badRegs = []
        badDst = []
        while True:
            popReg = self._find(Category.LOAD_REG, reg=reg, badDst=badRegs, dontModify=dontModify)
            if not popReg:
                raise RopChainError('Cannot build writewhatwhere gadget!')
            write4 = self._find(Category.WRITE_MEM, reg=popReg.category[2]['dst'],  badDst=
            badDst, srcdst='src')
            if not write4:
                badRegs.append(popReg.category[2]['dst'])
                continue
            else:
                popReg2 = self._find(Category.LOAD_REG, reg=write4.category[2]['dst'], dontModify=[popReg.category[2]['dst']]+dontModify)
                if not popReg2:
                    badDst.append(write4.category[2]['dst'])
                    continue
                else:
                    break;

        if len(what) % 8 > 0:
            what += ' ' * (8 - len(what) % 8)
        toReturn = ''
        for index in range(0,len(what),8):
            part = what[index:index+8]

            toReturn += self._printRopInstruction(popReg,False)
            toReturn += self._printAddString(part)
            regs = self._paddingNeededFor(popReg)
            for i in range(len(regs)):
                toReturn +=self._printPaddingInstruction()
            toReturn += self._printRopInstruction(popReg2, False)

            toReturn += self._printRebasedAddress(toHex(where+index,8), idx=idx)
            regs = self._paddingNeededFor(popReg2)
            for i in range(len(regs)):
                toReturn +=self._printPaddingInstruction()
            toReturn += self._printRopInstruction(write4)
        return (toReturn,popReg.category[2]['dst'], popReg2.category[2]['dst'])


    def _createWriteRegValueWhere(self, what, where, dontModify=[], idx=0):
        badRegs = []
        badDst = []
        while True:


            write4 = self._find(Category.WRITE_MEM, reg=what,  badDst=badDst, dontModify=dontModify, srcdst='src')
            if not write4:
                raise RopChainError('Cannot build writeregvaluewhere gadget!')
            else:
                popReg2 = self._find(Category.LOAD_REG, reg=write4.category[2]['dst'], dontModify=[what]+dontModify)
                if not popReg2:
                    badDst.append(write4.category[2]['dst'])
                    continue
                else:
                    break;

        toReturn = self._printRopInstruction(popReg2, False)
        toReturn += self._printRebasedAddress(toHex(where,8), idx=idx)
        regs = self._paddingNeededFor(popReg2)
        for i in range(len(regs)):
            toReturn +=self._printPaddingInstruction()
        toReturn += self._printRopInstruction(write4)

        return (toReturn,what, popReg2.category[2]['dst'])

    def _createLoadRegValueFrom(self, what, from_reg, dontModify=[], idx=0):
        try:
            return self._createLoadRegValueFromMov(what, from_reg, dontModify, idx)
        except RopChainError:
            return self._createLoadRegValueFromXchg(what, from_reg, dontModify, idx)

    def _createLoadRegValueFromMov(self, what, from_reg, dontModify=[], idx=0):
        badRegs = []
        badDst = []
        while True:


            load4 = self._find(Category.LOAD_MEM, reg=what,  badDst=badDst, dontModify=dontModify, srcdst='dst')
            if not load4:
                raise RopChainError('Cannot build loadwhere gadget!')
            else:
                popReg2 = self._find(Category.LOAD_REG, reg=load4.category[2]['src'], dontModify=[what,load4.category[2]['src']]+dontModify)
                if not popReg2:
                    badDst.append(load4.category[2]['src'])
                    continue
                else:
                    break;

        toReturn = self._printRopInstruction(popReg2, False)
        toReturn += self._printRebasedAddress(toHex(from_re,8), idx=idx)
        regs = self._paddingNeededFor(popReg2)
        for i in range(len(regs)):
            toReturn +=self._printPaddingInstruction()
        toReturn += self._printRopInstruction(load4)

        return (toReturn,what, popReg2.category[2]['dst'])

    def _createLoadRegValueFromXchg(self, what, from_reg, dontModify=[], idx=0):
        badRegs = []
        badDst = []
        while True:


            load4 = self._find(Category.XCHG_REG, reg=what,  badDst=badDst, dontModify=dontModify, srcdst='src')
            if not load4:
                raise RopChainError('Cannot build loadwhere gadget!')
            else:
                mov = self._find(Category.LOAD_MEM, reg=load4.category[2]['dst'],  badDst=badDst, dontModify=[load4.category[2]['dst']]+dontModify, srcdst='dst')
                if not mov:
                    badDst.append(load4.category[2]['dst'])
                    continue

                popReg2 = self._find(Category.LOAD_REG, reg=mov.category[2]['src'], dontModify=[what,load4.category[2]['src']]+dontModify)
                if not popReg2:
                    badDst.append(load4.category[2]['src'])
                    continue
                else:
                    break;



        toReturn = self._printRopInstruction(popReg2, False)
        toReturn += self._printRebasedAddress(toHex(from_reg,8), idx=idx)
        regs = self._paddingNeededFor(popReg2)
        for i in range(len(regs)):
            toReturn +=self._printPaddingInstruction()

        toReturn += self._printRopInstruction(mov)

        toReturn += self._printRopInstruction(load4)

        return (toReturn,what, popReg2.category[2]['dst'])

    def _createNumberSubtract(self, number, reg=None, badRegs=None, dontModify=None):
        if not badRegs:
            badRegs=[]
        while True:
            sub = self._find(Category.SUB_REG, reg=reg, badDst=badRegs, badSrc=badRegs, dontModify=dontModify)
            if not sub:
                raise RopChainError('Cannot build number with subtract gadget for reg %s!' % reg)
            popSrc = self._find(Category.LOAD_REG, reg=sub.category[2]['src'], dontModify=dontModify)
            if not popSrc:
                badRegs.append=[sub.category[2]['src']]
                continue
            popDst = self._find(Category.LOAD_REG, reg=sub.category[2]['dst'], dontModify=[sub.category[2]['src']]+dontModify)
            if not popDst:
                badRegs.append=[sub.category[2]['dst']]
                continue
            else:
                break;

        filler = self._createZeroByteFillerForSub(number)

        toReturn = self._printRopInstruction(popSrc, False)
        toReturn += self._printPaddingInstruction(toHex(filler,8))
        regs = self._paddingNeededFor(popSrc)
        for i in range(len(regs)):
            toReturn += self._printPaddingInstruction()
        toReturn += self._printRopInstruction(popDst, False)
        toReturn += self._printPaddingInstruction(toHex(filler+number,8))
        regs = self._paddingNeededFor(popDst)
        for i in range(len(regs)):
            toReturn += self._printPaddingInstruction()
        toReturn += self._printRopInstruction(sub)
        return (toReturn, popDst.category[2]['dst'],popSrc.category[2]['dst'])

    def _createNumberAddition(self, number, reg=None, badRegs=None, dontModify=None):
        if not badRegs:
            badRegs=[]
        while True:
            sub = self._find(Category.ADD_REG, reg=reg, badDst=badRegs, badSrc=badRegs, dontModify=dontModify)
            if not sub:
                raise RopChainError('Cannot build number with addition gadget for reg %s!' % reg)
            popSrc = self._find(Category.LOAD_REG, reg=sub.category[2]['src'], dontModify=dontModify)
            if not popSrc:
                badRegs.append=[sub.category[2]['src']]
                continue
            popDst = self._find(Category.LOAD_REG, reg=sub.category[2]['dst'], dontModify=[sub.category[2]['src']]+dontModify)
            if not popDst:
                badRegs.append(sub.category[2]['dst'])
                continue
            else:
                break;

        filler = self._createZeroByteFillerForAdd(number)

        toReturn = self._printRopInstruction(popSrc, False)
        toReturn += self._printPaddingInstruction(toHex(filler,8))
        regs = self._paddingNeededFor(popSrc)
        for i in range(len(regs)):
            toReturn += self._printPaddingInstruction()
        toReturn += self._printRopInstruction(popDst, False)
        toReturn += self._printPaddingInstruction(toHex(number - filler,8))
        regs = self._paddingNeededFor(popDst)
        for i in range(len(regs)):
            toReturn += self._printPaddingInstruction()
        toReturn += self._printRopInstruction(sub)

        return (toReturn, popDst.category[2]['dst'],popSrc.category[2]['dst'])

    def _createNumberPop(self, number, reg=None, badRegs=None, dontModify=None):
        if self._containsZeroByte(0xffffffff):
            raise RopChainError("Cannot write value with pop -1 and inc gadgets, because there are badbytes in the negated number")
        while True:
            popReg = self._find(Category.LOAD_REG, reg=reg, badDst=badRegs,dontModify=dontModify)
            if not popReg:
                raise RopChainError('Cannot build number with xor gadget!')
            incReg = self._find(Category.INC_REG, reg=popReg.category[2]['dst'], dontModify=dontModify)
            if not incReg:
                if not badRegs:
                    badRegs = []
                badRegs.append(popReg.category[2]['dst'])
            else:
                break

        value = self._printPaddingInstruction(toHex(0xffffffff,8))
        toReturn = self._printRopInstruction(popReg, value=value)
        for i in range(number+1):
            toReturn += self._printRopInstruction(incReg)

        return (toReturn ,popReg.category[2]['dst'],)


    def _createNumberXOR(self, number, reg=None, badRegs=None, dontModify=None):
        while True:
            clearReg = self._find(Category.CLEAR_REG, reg=reg, badDst=badRegs, badSrc=badRegs,dontModify=dontModify, srcEqDst=True)
            if not clearReg:
                raise RopChainError('Cannot build number with xor gadget!')
            if number > 0:
                incReg = self._find(Category.INC_REG, reg=clearReg.category[2]['src'], dontModify=dontModify)
                if not incReg:
                    if not badRegs:
                        badRegs = []
                    badRegs.append(clearReg.category[2]['src'])
                else:
                    break
            else:
                break

        toReturn = self._printRopInstruction(clearReg)
        for i in range(number):
            toReturn += self._printRopInstruction(incReg)

        return (toReturn, clearReg.category[2]['dst'],)

    def _createNumberXchg(self, number, reg=None, badRegs=None, dontModify=None):
        xchg = self._find(Category.XCHG_REG, reg=reg, badDst=badRegs, dontModify=dontModify)
        if not xchg:
            raise RopChainError('Cannot build number gadget with xchg!')

        other = xchg.category[2]['src'] if xchg.category[2]['dst'] else xchg.category[2]['dst']

        toReturn = self._createNumber(number, other, badRegs, dontModify)[0]

        toReturn += self._printRopInstruction(xchg)
        return (toReturn, reg, other)

    def _createNumberNeg(self, number, reg=None, badRegs=None, dontModify=None):
        if number == 0:
            raise RopChainError('Cannot build number gadget with neg if number is 0!')
        if self._containsZeroByte((~number)+1):
            raise RopChainError("Cannot use neg gadget, because there are badbytes in the negated number")
        neg = self._find(Category.NEG_REG, reg=reg, badDst=badRegs, dontModify=dontModify)
        if not neg:
            raise RopChainError('Cannot build number gadget with neg!')

        pop = self._find(Category.LOAD_REG, reg=reg, badDst=badRegs, dontModify=dontModify)
        if not pop:
            raise RopChainError('Cannot build number gadget with neg!')

        value = self._printPaddingInstruction(toHex((~number)+1, 8)) # two's complement
        toReturn = self._printRopInstruction(pop, value=value)
        toReturn += self._printRopInstruction(neg)
        return (toReturn, reg,)

    def _createNumber(self, number, reg=None, badRegs=None, dontModify=None, xchg=True):
        try:
            if self.containsBadbytes(number):
                try:
                    return self._createNumberNeg(number, reg, badRegs,dontModify)
                except RopChainError as e:

                    if number < 50:
                        try:
                            return self._createNumberXOR(number, reg, badRegs,dontModify)
                        except RopChainError:
                            try:
                                return self._createNumberPop(number, reg, badRegs,dontModify)
                            except RopChainError:
                                try:
                                    return self._createNumberSubtract(number, reg, badRegs,dontModify)
                                except RopChainError:
                                    return self._createNumberAddition(number, reg, badRegs,dontModify)

                    else :
                        try:
                            return self._createNumberSubtract(number, reg, badRegs,dontModify)
                        except RopChainError:
                            return self._createNumberAddition(number, reg, badRegs,dontModify)
            else:
                popReg =self._find(Category.LOAD_REG, reg=reg, badDst=badRegs,dontModify=dontModify)
                if not popReg:
                    raise RopChainError('Cannot build number gadget!')
                value = self._printPaddingInstruction(toHex(number,8))
                toReturn = self._printRopInstruction(popReg, value=value)
                return (toReturn , popReg.category[2]['dst'])
        except RopChainError:
            return self._createNumberXchg(number, reg, badRegs, dontModify)

    def _createAddress(self, address, reg=None, badRegs=None, dontModify=None):
        popReg = self._find(Category.LOAD_REG, reg=reg, badDst=badRegs,dontModify=dontModify)
        if not popReg:
            raise RopChainError('Cannot build address gadget!')

        toReturn = ''

        toReturn += self._printRopInstruction(popReg,False)
        toReturn += self._printRebasedAddress(toHex(address, 8), idx=self._usedBinaries.index((popReg.fileName, popReg.section)))
        regs = self._paddingNeededFor(popReg)
        for i in range(len(regs)):
            toReturn +=self._printPaddingInstruction()

        return (toReturn,popReg.category[2]['dst'])

    def _createSyscall(self, reg=None, badRegs=None, dontModify=None):
        syscall = self._find(Category.SYSCALL, reg=None, badDst=None, dontModify=dontModify)
        if not syscall:
            raise RopChainError('Cannot build syscall gadget!')

        toReturn = ''

        toReturn += self._printRopInstruction(syscall)

        return (toReturn,)

    def _createOpcode(self, opcode):
        gadget = self._searchOpcode(opcode)
         
        if gadget:
            if (gadget.fileName, gadget.section) not in self._usedBinaries:
                self._usedBinaries.append((gadget.fileName, gadget.section))
            return self._printRopInstruction(gadget)


    def _searchOpcode(self, opcode):
        r = Ropper()
        gadgets = []
        for section in self._binaries[0].executableSections:
            vaddr = section.virtualAddress
            gadgets.extend(r.searchOpcode(self._binaries[0],opcode=opcode,disass=True))

        if len(gadgets) > 0:
            return gadgets[0]
        else:
            raise RopChainError('Cannot create gadget for opcode: %s' % opcode)

    def _addressWidth(self):
        return 8

    def _writeCmdToMemory(self, cmd, where):
        # NUL-terminate + quad-word-align so the writewhatwhere gadget emits
        # whole quad-words and the buffer is a valid C string.
        return self._createWriteStringWhere(self._nulTerminateAndPad(cmd), where)[0]

    def create(self):
        pass


class RopChainSystemX86_64(RopChainX86_64):

    @classmethod
    def usableTypes(self):
        return (ELF, Raw)

    @classmethod
    def name(cls):
        return 'execve'

    def _createCommand(self, what, where, reg=None, dontModify=[], idx=0):
        if len(what) % 8 > 0:
            what = '/' * (8 - len(what) % 8) + what
        return self._createWriteStringWhere(what,where, idx=idx)

    def create(self, options):
        cmd = options.get('cmd')
        address = options.get('address')
        if not cmd:
            cmd = '/bin/sh'
        if len(cmd.split(' ')) > 1:
            raise RopChainError('No argument support for execve commands')

        self._printMessage('ROPchain Generator for syscall execve:\n')
        self._printMessage('\nwrite command into data section\nrax 0xb\nrdi address to cmd\nrsi address to null\nrdx address to null\n')
        chain = self._printHeader()
        gadgets = []
        can_create_command = False
        chain_tmp = '\n'
        if address is None:
            section = self._binaries[0].getSection('.data')

            length = math.ceil(float(len(cmd))/8) * 8
            nulladdress = section.offset+length
            try:
                cmdaddress = section.offset
                chain_tmp += self._createCommand(cmd,cmdaddress)[0]
                can_create_command = True

            except RopChainError as e:
                self._printMessage('Cannot create gadget: writewhatwhere')
                self._printMessage('Use 0x4141414141414141 as command address. Please replace that value.')
                cmdaddress = 0x4141414141414141
            if can_create_command:
                badregs = []
                tmpx = ''
                while True:

                    ret = self._createNumber(0x0, badRegs=badregs)
                    tmpx = ret[0]
                    try:
                        tmpx += self._createWriteRegValueWhere(ret[1], nulladdress)[0]
                        break
                    except BaseException as e:
                        #raise e
                        badregs.append(ret[1])

                chain_tmp += tmpx
                gadgets.append((self._createAddress, [cmdaddress],{'reg':'rdi'},['rdi','edi', 'di']))
                gadgets.append((self._createAddress, [nulladdress],{'reg':'rsi'},['rsi','esi', 'si']))
                gadgets.append((self._createAddress, [nulladdress],{'reg':'rdx'},['rdx','edx', 'dx', 'dl', 'dh']))
                gadgets.append((self._createNumber, [59],{'reg':'rax'},['rax','eax', 'ax', 'al', 'ah']))
        if address is not None and not can_create_command:
            if type(address) is str:
                cmdaddress = int(address, 16)
            nulladdress = options.get('nulladdress')
            if nulladdress is None:
                self._printMessage('No address to a null bytes was given, 0x4242424242424242 is used instead.')
                self._printMessage('Please replace that value.')
                nulladdress = 0x4242424242424242
            elif type(nulladdress) is str:
                nulladdress = int(nulladdress,16)

            gadgets.append((self._createNumber, [cmdaddress],{'reg':'rdi'},['rdi','edi', 'di']))
            gadgets.append((self._createNumber, [nulladdress],{'reg':'rsi'},['rsi','esi', 'si']))
            gadgets.append((self._createNumber, [nulladdress],{'reg':'rdx'},['rdx','edx', 'dx', 'dl', 'dh']))
            gadgets.append((self._createNumber, [59],{'reg':'rax'},['rax','eax', 'ax', 'al', 'ah']))

        self._printMessage('Try to create chain which fills registers without delete content of previous filled registers')
        chain_tmp += self._createDependenceChain(gadgets)

        try:
            self._printMessage('Look for syscall gadget')
            chain_tmp += self._createSyscall()[0]
            self._printMessage('syscall gadget found')

        except RopChainError:
            try:
                self._printMessage('No syscall gadget found!')
                self._printMessage('Look for syscall opcode')

                chain_tmp += self._createOpcode('0f05')
                self._printMessage('syscall opcode found')

            except RopChainError:
                chain_tmp += '# INSERT SYSCALL GADGET HERE\n'
                self._printMessage('syscall opcode not found')


        chain += self._printRebase()
        chain += 'rop = \'\'\n'

        chain += chain_tmp
        chain += 'print(rop)'
        return chain


class RopChainSpawnShellX86_64(RopChainX86_64):
    """Generate a ret2libc ``system('/bin/sh')`` chain for x86_64 (System V).

    The first integer argument goes in ``rdi``::

        [ pop rdi ; ret ]   (loads &"/bin/sh"; placeholder if absent)
        [ &"/bin/sh"    ]
        [ ret           ]   <- 16-byte stack-alignment ret for glibc movaps
        [ &system       ]

    Modern glibc ``system()`` executes ``movaps`` against a 16-byte aligned
    stack; the extra bare ``ret`` realigns it.  Pass ``align=false`` to omit."""

    @classmethod
    def usableTypes(self):
        return (ELF, Raw)

    @classmethod
    def name(cls):
        return 'spawn_shell'

    def create(self, options=None):
        options = options or {}
        cmd = options.get('cmd') or '/bin/sh'
        address = options.get('address')
        string = options.get('string')
        align_opt = options.get('align')
        align = True
        if align_opt is not None:
            align = str(align_opt).lower() not in ('0', 'false', 'no', 'off')

        self._printMessage('ROPchain Generator for system() on x86_64 (ret2libc):')
        self._printMessage('  rdi = &"/bin/sh", then call system()')

        defs = ''
        body = '\n'

        binsh_line, binsh_defs, write_text = self._resolveBinshPointer(cmd, string)
        defs += binsh_defs
        body += write_text

        # pop rdi ; ret -> rdi = &"/bin/sh"
        pop_rdi = self._find(Category.LOAD_REG, reg='rdi')
        if pop_rdi is not None:
            body += self._printRopInstruction(pop_rdi, padding=True, value=binsh_line)
        else:
            self._printMessage('No `pop rdi ; ret` gadget found; emitting placeholder.')
            body += '# INSERT `pop rdi ; ret` GADGET HERE\n'
            body += binsh_line

        # Optional 16-byte stack alignment ret (glibc system() uses movaps).
        if align:
            try:
                body += '# 16-byte stack alignment for glibc system() (movaps):\n'
                body += self._createOpcode('c3')
            except RopChainError:
                self._printMessage('No `ret` gadget for stack alignment; skipping.')
                body += '# (no `ret` gadget found for alignment)\n'

        system_line, system_defs = self._resolveSystemAddress(address)
        defs += system_defs
        body += system_line

        chain = self._printHeader()
        chain += self._printRebase()
        chain += defs
        chain += "rop = ''\n"
        chain += body
        chain += 'print(rop)\n'
        return chain


class RopChainMprotectX86_64(RopChainX86_64):
    """
    Builds a ropchain for mprotect syscall
    rax 0x7b
    rdi address
    rsi size
    rdx 0x7 -> RWE
    """

    @classmethod
    def usableTypes(self):
        return (ELF, Raw)

    @classmethod
    def name(cls):
        return 'mprotect'

    def _createJmp(self, reg=['rsp']):
        r = Ropper()
        gadgets = []
        for section in self._binaries[0].executableSections:
            vaddr = section.virtualAddress
            gadgets.extend(r.searchJmpReg(self._binaries[0],reg))



        if len(gadgets) > 0:
            if (gadgets[0].fileName, gadgets[0].section) not in self._usedBinaries:
                self._usedBinaries.append((gadgets[0].fileName, gadgets[0].section))
            return self._printRopInstruction(gadgets[0])
        else:
            return None

    def __extract(self, param):
        if not match('0x[0-9a-fA-F]{1,16},0x[0-9a-fA-F]+', param) or not match('0x[0-9a-fA-F]{1,16},[0-9]+', param):
            raise RopChainError('Parameter have to have the following format: <hexnumber>,<hexnumber> or <hexnumber>,<number>')

        split = param.split(',')
        if isHex(split[1]):
            return (int(split[0], 16), int(split[1], 16))
        else:
            return (int(split[0], 16), int(split[1], 10))


    def create(self, options={}):
        address = options.get('address')
        size = options.get('size')
        if not address:
            raise RopChainError('Missing parameter: address')
        if not size:
            raise RopChainError('Missing parameter: size')

        if not match('0x[0-9a-fA-F]{1,8}', address):
            raise RopChainError('Parameter address have to have the following format: <hexnumber>')

        if not match('0x[0-9a-fA-F]+', size):
            raise RopChainError('Parameter size have to have the following format: <hexnumber>')

        address = int(address, 16)
        size = int(size, 16)

        self._printMessage('ROPchain Generator for syscall mprotect:\n')
        self._printMessage('rax 0xa\nrdi address\nrsi size\nrdx 0x7 -> RWE\n')

        chain = self._printHeader()

        chain += 'shellcode = \'\\xcc\'*100\n\n'

        gadgets = []
        gadgets.append((self._createNumber, [address],{'reg':'rdi'},['rdi','edi', 'di']))
        gadgets.append((self._createNumber, [size],{'reg':'rsi'},['rsi','esi', 'si']))
        gadgets.append((self._createNumber, [0x7],{'reg':'rdx'},['rdx','edx', 'dx', 'dl', 'dh']))
        gadgets.append((self._createNumber, [0xa],{'reg':'rax'},['rax','eax', 'ax', 'al', 'ah']))

        self._printMessage('Try to create chain which fills registers without delete content of previous filled registers')
        chain_tmp = ''
        chain_tmp += self._createDependenceChain(gadgets)
        try:
            self._printMessage('Look for syscall gadget')
            chain_tmp += self._createSyscall()[0]
            self._printMessage('syscall gadget found')
        except RopChainError:
            chain_tmp += '\n# ADD HERE SYSCALL GADGET\n\n'
            self._printMessage('No syscall gadget found!')

        self._printMessage('Look for jmp esp')
        jmp_esp = self._createJmp()
        if jmp_esp:
            self._printMessage('jmp esp found')
            chain_tmp += jmp_esp
        else:
            self._printMessage('no jmp esp found')
            chain_tmp += '\n# ADD HERE JMP ESP\n\n'

        chain += self._printRebase()
        chain += '\nrop = \'\'\n'
        chain += chain_tmp
        chain += 'rop += shellcode\n\n'
        chain += 'print(rop)\n'

        return chain


class RopChainRet2CsuX86_64(RopChainX86_64):
    """Search for and generate ret2csu gadgets from __libc_csu_init.

    __libc_csu_init contains two gadget sequences useful for controlling
    the first three x86-64 calling convention arguments (rdi, rsi, rdx)
    through registers loaded from the stack:

    Gadget 1 (setup/pop):
        pop rbx; pop rbp; pop r12; pop r13; pop r14; pop r15; ret

    Gadget 2 (dispatch/call):
        mov rdx, r14|r15; mov rsi, r13|r14; mov edi, r12d|r13d;
        call qword ptr [r15|r12 + rbx*8]

    The exact register mapping depends on compiler version.  This
    generator locates both gadget halves in the binary and emits a
    chain that calls an arbitrary function pointer with controlled
    rdi, rsi, and rdx.
    """

    # Known register mappings for different compiler versions.
    _VARIANTS = [
        # newer GCC (>= ~5): mov rdx,r14; mov rsi,r13; mov edi,r12d; call [r15+rbx*8]
        {'rdx': 'r14', 'rsi': 'r13', 'edi': 'r12', 'call_base': 'r15'},
        # older GCC (< ~5):  mov rdx,r15; mov rsi,r14; mov edi,r13d; call [r12+rbx*8]
        {'rdx': 'r15', 'rsi': 'r14', 'edi': 'r13', 'call_base': 'r12'},
        # alternative older:  mov rdx,r13; mov rsi,r14; mov edi,r15d; call [r12+rbx*8]
        {'rdx': 'r13', 'rsi': 'r14', 'edi': 'r15', 'call_base': 'r12'},
    ]

    @classmethod
    def usableTypes(self):
        return (ELF, Raw)

    @classmethod
    def name(cls):
        return 'ret2csu'

    # Byte patterns for gadget 1: pop rbx; pop rbp; pop r12; pop r13; pop r14; pop r15; ret
    _GADGET1_BYTES = b'\x5b\x5d\x41\x5c\x41\x5d\x41\x5e\x41\x5f\xc3'

    # Byte patterns for the dispatch gadget (mov rdx; mov rsi; mov edi) per variant
    _DISPATCH_BYTES = [
        # newer GCC: mov rdx,r14; mov rsi,r13; mov edi,r12d
        (b'\x4c\x89\xf2\x4c\x89\xee\x44\x89\xe7', 0),
        # older GCC: mov rdx,r15; mov rsi,r14; mov edi,r13d
        (b'\x4c\x89\xfa\x4c\x89\xf6\x44\x89\xef', 1),
        # alternative: mov rdx,r13; mov rsi,r14; mov edi,r15d
        (b'\x4c\x89\xea\x4c\x89\xf6\x44\x89\xff', 2),
    ]

    def _findCsuGadgets(self):
        """Locate the two ret2csu gadget halves in the binary.

        Uses raw byte pattern matching to find candidates, then verifies
        with capstone disassembly.  Returns (gadget1_addr, gadget2_addr,
        variant) or raises RopChainError.
        """
        binary = self._binaries[0]
        md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
        md.detail = False

        gadget1_addr = None
        gadget2_addr = None
        matched_variant = None

        for section in binary.executableSections:
            code = bytes(bytearray(section.bytes))
            base = section.virtualAddress

            # Search for gadget 1
            if gadget1_addr is None:
                idx = code.find(self._GADGET1_BYTES)
                while idx >= 0:
                    addr = base + idx
                    snippet = list(md.disasm(code[idx:idx+len(self._GADGET1_BYTES)+2], addr))
                    if (len(snippet) >= 7
                            and snippet[0].mnemonic == 'pop' and snippet[0].op_str == 'rbx'
                            and snippet[1].mnemonic == 'pop' and snippet[1].op_str == 'rbp'
                            and snippet[2].mnemonic == 'pop' and snippet[2].op_str == 'r12'
                            and snippet[3].mnemonic == 'pop' and snippet[3].op_str == 'r13'
                            and snippet[4].mnemonic == 'pop' and snippet[4].op_str == 'r14'
                            and snippet[5].mnemonic == 'pop' and snippet[5].op_str == 'r15'
                            and snippet[6].mnemonic == 'ret'):
                        gadget1_addr = addr
                        break
                    idx = code.find(self._GADGET1_BYTES, idx + 1)

            # Search for gadget 2 (dispatch)
            if matched_variant is None:
                for pattern, variant_idx in self._DISPATCH_BYTES:
                    idx = code.find(pattern)
                    while idx >= 0:
                        addr = base + idx
                        snippet = list(md.disasm(code[idx:idx+20], addr))
                        if (len(snippet) >= 4
                                and snippet[0].mnemonic == 'mov'
                                and snippet[1].mnemonic == 'mov'
                                and snippet[2].mnemonic == 'mov'
                                and snippet[3].mnemonic == 'call'
                                and 'qword ptr' in snippet[3].op_str
                                and 'rbx*8' in snippet[3].op_str):
                            gadget2_addr = addr
                            matched_variant = self._VARIANTS[variant_idx]
                            break
                        idx = code.find(pattern, idx + 1)
                    if matched_variant is not None:
                        break

        if gadget1_addr is not None and gadget2_addr is not None and matched_variant is not None:
            return (gadget1_addr, gadget2_addr, matched_variant)

        raise RopChainError(
            'Could not find ret2csu gadgets (__libc_csu_init) in the binary. '
            'The binary may be statically linked without csu or compiled with '
            'a non-standard toolchain.')

    def create(self, options=None):
        options = options or {}

        self._printMessage('ROPchain Generator for ret2csu (__libc_csu_init):\n')
        self._printMessage('Searching for __libc_csu_init gadgets...')

        gadget1_addr, gadget2_addr, variant = self._findCsuGadgets()

        self._printMessage('Found gadget 1 (setup) at %s' % toHex(gadget1_addr, 8))
        self._printMessage('Found gadget 2 (dispatch) at %s' % toHex(gadget2_addr, 8))
        self._printMessage('Variant: mov rdx,%s; mov rsi,%s; mov edi,%sd; '
                           'call [%s+rbx*8]'
                           % (variant['rdx'], variant['rsi'],
                              variant['edi'], variant['call_base']))

        # Determine register assignments from variant
        rdx_src = variant['rdx']
        rsi_src = variant['rsi']
        edi_src = variant['edi']
        call_base = variant['call_base']

        # Parse options
        func_ptr = options.get('func_ptr')
        arg1 = options.get('arg1', '0x0')
        arg2 = options.get('arg2', '0x0')
        arg3 = options.get('arg3', '0x0')
        call_addr = options.get('call')

        # Register the primary binary for rebasing
        idx = self._useBinaryForRebase()

        chain = self._printHeader()
        chain += self._printRebase()

        chain += ('\n')
        chain += ('# ret2csu gadgets from __libc_csu_init\n')
        chain += ('# Gadget 1 (setup): pop rbx; pop rbp; pop r12; pop r13; pop r14; pop r15; ret\n')
        chain += ('# Gadget 2 (dispatch): mov rdx,%s; mov rsi,%s; mov edi,%sd; call [%s+rbx*8]\n'
                  % (rdx_src, rsi_src, edi_src, call_base))
        chain += ('\n')

        g1_off = gadget1_addr - self._binaries[0].imageBase
        g2_off = gadget2_addr - self._binaries[0].imageBase

        chain += ('CSU_GADGET1 = %s # pop rbx..r15; ret\n' % toHex(g1_off, 8))
        chain += ('CSU_GADGET2 = %s # mov rdx,%s; mov rsi,%s; mov edi,%sd; call [%s+rbx*8]\n\n'
                  % (toHex(g2_off, 8), rdx_src, rsi_src, edi_src, call_base))

        if func_ptr:
            chain += ('FUNC_PTR = %s # address of pointer to function to call\n' % func_ptr)
        else:
            chain += ('FUNC_PTR = 0x4141414141414141 # TODO: address of pointer to function to call\n')
            self._printMessage('No func_ptr given. Set func_ptr= to the address of a POINTER '
                               'to the function you want to call (e.g. a GOT entry).')

        if call_addr:
            chain += ('CALL_ADDR = %s # address to call/return to after dispatch\n' % call_addr)
        else:
            chain += ('CALL_ADDR = 0x4242424242424242 # TODO: address to jump to after the csu call\n')

        chain += ('\n')
        chain += ('def csu_call(func_ptr, arg1, arg2, arg3):\n')
        chain += ('    """Build a ret2csu payload fragment.\n')
        chain += ('    func_ptr: address of a POINTER to the target function (e.g. GOT entry)\n')
        chain += ('    arg1: rdi value (truncated to 32 bits by mov edi,...)\n')
        chain += ('    arg2: rsi value\n')
        chain += ('    arg3: rdx value\n')
        chain += ('    """\n')
        chain += ('    payload  = b""\n')
        chain += ('    # Gadget 1: load registers from the stack\n')
        chain += ('    payload += rebase_%d(CSU_GADGET1)\n' % idx)
        chain += ('    payload += p(0x0)                # rbx = 0 (index into call table)\n')
        chain += ('    payload += p(0x1)                # rbp = 1 (loop counter, ensures single call)\n')

        # Assign the correct pop slots based on variant
        pop_order = ['r12', 'r13', 'r14', 'r15']
        slot_map = {}
        slot_map[edi_src] = 'arg1'
        slot_map[rsi_src] = 'arg2'
        slot_map[rdx_src] = 'arg3'
        slot_map[call_base] = 'func_ptr'

        for reg in pop_order:
            if reg in slot_map:
                chain += ('    payload += p(%s)%s# %s -> %s\n'
                          % (slot_map[reg],
                             ' ' * (16 - len('p(%s)' % slot_map[reg])),
                             reg, slot_map[reg]))
            else:
                chain += ('    payload += p(0xdeadbeef)     # %s (unused)\n' % reg)

        chain += ('\n')
        chain += ('    # Gadget 2: dispatch -- moves registers and calls [%s+rbx*8]\n' % call_base)
        chain += ('    payload += rebase_%d(CSU_GADGET2)\n' % idx)
        chain += ('\n')
        chain += ('    # After the call returns, __libc_csu_init increments rbx and\n')
        chain += ('    # compares it against rbp; since rbx=0+1==rbp=1 the loop exits\n')
        chain += ('    # and falls through to another pop sequence:\n')
        chain += ('    #   add rsp, 8; pop rbx; pop rbp; pop r12; pop r13; pop r14; pop r15; ret\n')
        chain += ('    payload += p(0x0)                # add rsp,8 padding\n')
        chain += ('    payload += p(0x0)                # rbx\n')
        chain += ('    payload += p(0x0)                # rbp\n')
        chain += ('    payload += p(0x0)                # r12\n')
        chain += ('    payload += p(0x0)                # r13\n')
        chain += ('    payload += p(0x0)                # r14\n')
        chain += ('    payload += p(0x0)                # r15\n')
        chain += ('\n')
        chain += ('    return payload\n')
        chain += ('\n')
        chain += ('rop = b""\n')
        chain += ('rop += csu_call(FUNC_PTR, %s, %s, %s)\n' % (arg1, arg2, arg3))
        chain += ('rop += p(CALL_ADDR)             # return address after csu dispatch\n')
        chain += ('\n')
        chain += ('print(rop)\n')

        self._printMessage('')
        self._printMessage('ret2csu chain generated!')
        self._printMessage('Register mapping for this binary:')
        self._printMessage('  rdi (arg1) <- %s (32-bit: mov edi, %sd)' % (edi_src, edi_src))
        self._printMessage('  rsi (arg2) <- %s' % rsi_src)
        self._printMessage('  rdx (arg3) <- %s' % rdx_src)
        self._printMessage('  call target <- [%s + rbx*8]' % call_base)

        return chain
